Repository CaioRobs/BarbeariaAlura, pull requests merged in 2021-05, with the labels that each got.

#1 novo alorra
  alorra.js
Labels: enhancement

#2 adds comment
  alorra.js
Labels: comment

#3 Arquivos do site da Barbearia
  alorra.js
  banner.jpg
  barba.jpg
  beneficios.jpg
  bg.jpg
  cabelo+barba.jpg
  cabelo.jpg
  home.css
  index.html
  logo-branco.png
  logo.png
  produtos.css
  produtos.html
  reset.css
Labels: help wanted

#4 Feat/some improvements
  images/banner.jpg
  images/barba.jpg
  images/beneficios.jpg
  images/bg.jpg
  images/cabelo+barba.jpg
  images/cabelo.jpg
  images/logo-branco.png
  images/logo.png
  index.html
  pages/contato.html
  pages/home.css
  pages/produtos.css
  pages/produtos.html
  pages/reset.css
  produtos.html
Labels: enhancement

#7 Develop
  README.md
  images/banner.jpg
  images/barba.jpg
  images/beneficios.jpg
  images/bg.jpg
  images/cabelo+barba.jpg
  images/cabelo.jpg
  images/logo-branco.png
  images/logo.png
  index.html
  pages/contato.html
  pages/home.css
  pages/index.html
  pages/produtos.css
  pages/produtos.html
  pages/reset.css
  produtos.css
  produtos.html
Labels: enhancement

#9 Adds bootstrap to our project
  .gitignore
  package-lock.json
  pages/contato.html
Labels: enhancement

#8 Imagem do background nao estava aparecendo
  .gitignore
  package-lock.json
  pages/contato.html
  pages/header-footer-style.css
  pages/home-style.css
  pages/index.html
  pages/produtos.html
  pages/style.css
Labels: comment, help wanted

#10 Formularios para contato adicionados
  pages/contato.html
Labels: enhancement

#11 Applies bootstrap grid in Products page
  pages/contato.html
  pages/produtos.html
  pages/style.css
Labels: enhancement

#12 Feat/bootstrap index
  images/corleone-banner.jpeg
  pages/home-style.css
  pages/index.html
  pages/style.css
Labels: enhancement

#13 fixes mobile rendering
  pages/home-style.css
  pages/index.html
  pages/produtos.html
  pages/style.css
Labels: enhancement
